### ISSUE TITLE
create HPO database

### ISSUE THREAD

**Issue by dridk** [lasigeBioTM/DiShIn#2]
Hi, 

Did success to create a database with HPO : (https://hpo.jax.org/app/download/ontology ) 
It seems empty : 

```python
ssmpy.create_semantic_base("hp.owl", "hp3.db", "http://purl.obolibrary.org/obo/", "http://www.w3.org/2000/01/rdf-schema#subClassOf", "list.txt")
ssmpy.semantic_base("hp3.db")
ssmpy.get_id("HP:0006855") # => -1 
``` 

Could you tell where I am wrong ? It may come from the prefix ? the relation ?

**Comment by AndreLamurias** [comment]
The ":" characters of the ontology  ID are replaced with a "_", so if you try with HP_0006855 it should work. This was done for compatibility reasons.

**Comment by dridk** [comment]
Hi, thx .
I will try but I am not sure. The database looks empty

Le jeu. 7 mai 2020 à 15:23, André Lamúrias <notifications@github.com> a
écrit :

**Comment by AndreLamurias** [comment]
if it's really empty let me know, could be some issue with the HPO file you're using. I just tried that example with the latest version and it worked for me.

**Comment by dridk** [comment]
It works ! tx!
